export const subscriptionDetails = [
  {
    name: 'Basic',
    description: 'Get started fast. No credit card required.',
    monthlyPrice: 0,
    yearlyPrice: 0,
    monthlyLink: null,
    yearlyLink: null,
    features: [
      'Ads visible on the page',
      'Create palettes up to 5 colors',
      'Save up to 10 color palettes',
      'Generate 1 color system per month',
      'Save up to 1 color system',
      'Generation prompts limited to 200 characters',
      'Image to palette generation',
      'Limited color space options',
    ],
  },
  {
    name: 'Pro',
    description: 'Unlock your creativity. Ideal for designers and hobbyists.',
    monthlyPrice: 5,
    yearlyPrice: 4,
    monthlyLink: process.env.NEXT_PUBLIC_STRIPE_PRO_MONTHLY_LINK,
    yearlyLink: process.env.NEXT_PUBLIC_STRIPE_PRO_YEARLY_LINK,
    features: [
      'Ad-free experience',
      'Create palettes up to 10 colors',
      'Save up to 50 color palettes',
      'Generate 25 color systems per month',
      'Save up to 50 color systems',
      'Generation prompts up to 500 characters',
      'Advanced image to palette generation',
      'Extended color space options',
      'Access to our Glimpse AI based on gpt 4o-mini',
      'Export palettes in advanced formats',
    ],
  },
  {
    name: 'Max',
    description: 'Unlimited possibilities. For dedicated professionals.',
    monthlyPrice: 9,
    yearlyPrice: 7,
    monthlyLink: process.env.NEXT_PUBLIC_STRIPE_MAX_MONTHLY_LINK,
    yearlyLink: process.env.NEXT_PUBLIC_STRIPE_MAX_YEARLY_LINK,
    features: [
      'All Pro features',
      'Create palettes with unlimited colors',
      'Unlimited color palette and system storage',
      'Unlimited color system generation',
      'Generation prompts up to 1000 characters',
      'Access to latest AI models for color creation',
    ],
  },
];
